version: '3.8'
services:
  database:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=imobiliaria
      - MYSQL_ROOT_PASSWORD=123456789
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  database:
    driver: local